//**** SET PACKAGE ****\\
package models;

//*** IMPORT PACKAGES ****\\
import core.CustomArray;

//**** START CLASS ****\\
//The AdminUser class extends the main user class and is dynamically generated by the load() method in the users model for admin users that
//have the admin flag in the csv, admin users is the same as users but with the addon of a session log that stores what the user has
//done during the current session that they have been on the application for. This applies to importing the messages.csv
public class AdminUser extends User{

    //declare our final custom array admin log array
    private final CustomArray adminLog;

    //**** CONSTRUCTOR ****\\
    //the constructor of this child class accepts all the values of the parent class and parses them to the parent via the super() call
    public AdminUser(String username, String password, String fullname, long registrationDate, boolean isAdmin) {
        super(username, password, fullname, registrationDate, isAdmin);
        //create our admin log object.
        this.adminLog = new CustomArray(String.class);
    }

    //**** GET LOG ****\\
    //this method is called by a controller to be parsed to a view and returns the log in the form of a string
    public String getLog(){
        //create the outcome to be returned
        String outcome = "";

        //create our i counter
        int i = 0;
        //set up our while loop to count over all our log entires
        while(i < adminLog.length()){
            //add the key and values to the outcome
            outcome += adminLog.getKeys()[i]+":"+adminLog.getValues()[i]+",";
            //increase our iteration whilst we are less than the admin length
            i++;
        }
        //finally return the outcome;
        return outcome;
    }

    //**** LOG ****\\
    //this method logs a action, it accepts a value and a key as permameters
    public void log(String key, String value){
        //add the value and key to the log
        this.adminLog.add(value, key);
    }
}
